-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Products_menu"
(
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    "Price" money NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Cart Table"
(
    "ProductId" integer NOT NULL,
    "Qty" numeric NOT NULL,
    PRIMARY KEY ("ProductId")
);

CREATE TABLE IF NOT EXISTS public."Users"
(
    "User_id" serial NOT NULL,
    "Username" character varying(50) NOT NULL,
    PRIMARY KEY ("User_id")
);

CREATE TABLE IF NOT EXISTS public."Order_Header"
(
    "Order_id" integer NOT NULL,
    users integer NOT NULL,
    order_date date NOT NULL,
    PRIMARY KEY ("Order_id")
);

CREATE TABLE IF NOT EXISTS public."Order_details"
(
    "Order_Header" integer NOT NULL,
    "Product_id" integer NOT NULL,
    "Qty" integer NOT NULL
);

ALTER TABLE IF EXISTS public."Cart Table"
    ADD CONSTRAINT "ProductId" FOREIGN KEY ("ProductId")
    REFERENCES public."Products_menu" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Order_details"
    ADD CONSTRAINT "Order_header" FOREIGN KEY ("Order_Header", "Product_id")
    REFERENCES public."Order_Header" ("Order_id", id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Order_details"
    ADD CONSTRAINT "Pr" FOREIGN KEY ("Product_id")
    REFERENCES public."Products_menu" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;